apiVersion: v1
kind: Service
metadata:
  name: guestbooksvc
  labels:
    app: guestbook
spec:
  type: ClusterIP
  ports:
  - targetPort: 3000
    port: 8080
    name: app-port
    protocol: TCP
  selector:
    app: guestbook
